from __future__ import annotations

import asyncio
import copy
import json
import logging
import os
import random
import re
import threading
import time
from collections import deque
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal
from urllib.parse import urljoin

import aiohttp
from genai_pyo3 import (
    ChatMessage,
    ChatOptions,
    ChatRequest,
    ChatResponse,
    Client,
    JsonSpec,
    StreamEnd,
    Tool,
    Usage,
)
from pydantic import BaseModel, ConfigDict, RootModel

from .budget import (
    BudgetReservation,
    SpendLedger,
    current_spend_metadata,
)

logger = logging.getLogger(__name__)

# Per-file hunter runs can legitimately take up to ~a day against a slow local
# model (large tier-A budgets, big files), so the socket-level read timeout
# needs to be long enough to survive that instead of the "Timeout on reading
# data from socket" errors seen when the underlying genai-pyo3 defaults were
# left unset. connect_timeout_seconds is kept short-ish since establishing the
# TCP/TLS connection itself should never take long, even over a flaky
# link-local hop; it's only widened a bit for headroom.
_LLM_CONNECT_TIMEOUT_SECONDS: float = 60.0
_LLM_READ_TIMEOUT_SECONDS: float = 86_400.0  # 24h
_LLM_TOTAL_TIMEOUT_SECONDS: float = 90_000.0  # 25h, headroom over read timeout


class ToolInputModel(BaseModel):
    """Base for provider-facing tool inputs generated by Pydantic."""

    model_config = ConfigDict(extra="forbid")


# Per-call LLM progress logging. Off by default so the 26 other callers stay
# quiet; flip on with CLEARWING_LLM_LOG=1 to log every achat with timing +
# token usage at INFO.
_LOG_CALLS = os.environ.get("CLEARWING_LLM_LOG") not in (None, "", "0")

# Ring buffer of the most recent calls + running totals, populated only when
# _LOG_CALLS is set. Feeds the live rich activity panel (ui/llm_activity.py).
# Guarded by a lock since sourcehunt fans hunters out concurrently and the
# panel repaints from a separate refresh thread.
_CALL_LOCK = threading.Lock()
_RECENT_CALLS: deque[dict[str, Any]] = deque(maxlen=5)
_SPINNER_FRAMES = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"
_SPINNER_IDX: int = 0
_CALL_TOTALS = {
    "calls": 0,
    "input_tokens": 0,
    "cached_tokens": 0,
    "output_tokens": 0,
    "failures": 0,
}


def _record_call(
    model: str,
    elapsed_ms: int,
    input_tokens: int | None,
    output_tokens: int | None,
    tool_calls: int,
    ok: bool,
    cached_tokens: int | None = 0,
) -> None:
    """Append one call to the ring buffer and bump running totals.

    ``cached_tokens`` is the subset of ``input_tokens`` served from the
    provider's prompt cache; the panel bills those at the cheaper cached rate.
    """
    with _CALL_LOCK:
        _CALL_TOTALS["calls"] += 1
        if ok:
            _CALL_TOTALS["input_tokens"] += input_tokens or 0
            _CALL_TOTALS["cached_tokens"] += cached_tokens or 0
            _CALL_TOTALS["output_tokens"] += output_tokens or 0
        else:
            _CALL_TOTALS["failures"] += 1
        _RECENT_CALLS.append(
            {
                "model": model,
                "elapsed_ms": elapsed_ms,
                "input_tokens": input_tokens,
                "cached_tokens": cached_tokens,
                "output_tokens": output_tokens,
                "tool_calls": tool_calls,
                "ok": ok,
                "ts": datetime.now().strftime("%H:%M:%S.%f")[:11],
            }
        )


def recent_call_stats() -> dict[str, Any]:
    """Snapshot of running totals + the last few calls, for live display."""
    with _CALL_LOCK:
        return {"totals": dict(_CALL_TOTALS), "recent": list(_RECENT_CALLS)}


def call_logging_enabled() -> bool:
    """True when CLEARWING_LLM_LOG is set (per-call logging + live panel)."""
    return _LOG_CALLS


# ---------------------------------------------------------------------------
# reasoning_effort auto-detection
# ---------------------------------------------------------------------------
#
# `reasoning_effort` is an OpenAI-reasoning-only parameter. Most non-OpenAI
# OpenAI-compat endpoints reject it with HTTP 400 when the configured model is
# not reasoning-capable (Groq + Llama is the common case). We default to
# omitting it for model families we know reject it, while preserving the
# previous "medium" default for everything else.
#
# Match semantics: case-insensitive substring against the model name. First
# match wins; order is not significant.
_REASONING_EFFORT_UNSUPPORTED_PATTERNS: tuple[str, ...] = (
    "llama-3",
    "llama-4",
    "mistral",
    "mixtral",
    "qwen2",
    "gemma",
    "glm",
)

# Explicit re-enable list for model names that contain an unsupported pattern
# above but actually *do* support reasoning_effort (e.g. reasoning-tuned
# variants of a denylisted family). Compared against the full lowercased model
# name. Intentionally empty today; populate as such models ship.
_REASONING_EFFORT_OVERRIDE_ALLOW: frozenset[str] = frozenset()

# Models that must NOT be sent ChatOptions(capture_reasoning_content=True):
# genai-pyo3 / the backend errors when reasoning capture is requested for them.
# Everything else supports it, so we capture reasoning by default and only skip
# for names matching this list. Case-insensitive substring match on the model
# name. Add new offenders here as they surface.
_REASONING_CAPTURE_UNSUPPORTED_PATTERNS: tuple[str, ...] = (
    "gpt-5.3-codex-spark",
)


def _model_supports_reasoning_capture(model_name: str) -> bool:
    """False when *model_name* rejects reasoning-content capture (blacklist)."""
    lower = model_name.lower()
    return not any(pattern in lower for pattern in _REASONING_CAPTURE_UNSUPPORTED_PATTERNS)


def _run_coro_sync(coro):
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)
    raise RuntimeError("Synchronous wrapper called from a running event loop")


def response_text(response: ChatResponse) -> str:
    """Coalesce a :class:`ChatResponse`'s text segments into a single string.

    Prefers ``first_text()`` when it is non-empty; falls back to joining
    every non-empty segment in ``texts()``. Returns ``""`` when the
    response carries no text at all (e.g. a pure tool-call response).
    """
    first = response.first_text
    if first:
        return first
    return "\n".join(segment for segment in response.texts if segment)


def _is_root_model_type(schema_model: type[BaseModel]) -> bool:
    return issubclass(schema_model, RootModel)


def _validate_schema_response(schema_model: type[BaseModel], text: str) -> BaseModel:
    if not text or not text.strip():
        raise ValueError("LLM returned empty response; expected JSON matching " + schema_model.__name__)
    try:
        return schema_model.model_validate_json(text)
    except Exception:
        parsed_json = json.loads(text)
        if isinstance(parsed_json, list) and "results" in schema_model.model_fields:
            return schema_model.model_validate({"results": parsed_json})
        raise


@dataclass(slots=True)
class NativeToolSpec:
    name: str
    description: str
    schema: dict[str, Any]
    handler: Any

    async def ainvoke(self, arguments: dict[str, Any]) -> Any:
        if asyncio.iscoroutinefunction(self.handler):
            return await self.handler(**arguments)
        return await asyncio.to_thread(self.handler, **arguments)

    def invoke(self, arguments: dict[str, Any] | None = None) -> Any:
        return _run_coro_sync(self.ainvoke(arguments or {}))

    @property
    def input_schema(self) -> dict[str, Any]:
        return self.schema


class AsyncLLMClient:
    """Native async wrapper around genai-pyo3 for sourcehunt/runtime use.

    This intentionally bypasses LangChain's message/result model and exposes
    only the pieces Clearwing actually needs: text, tool calls, usage, and
    bounded concurrency.
    """

    @staticmethod
    def _auto_resolve_reasoning_effort(model_name: str) -> str | None:
        """Return the effective reasoning_effort for *model_name*.

        Returns ``None`` (i.e. omit the parameter) when the model name matches
        a pattern in :data:`_REASONING_EFFORT_UNSUPPORTED_PATTERNS` and is not
        in :data:`_REASONING_EFFORT_OVERRIDE_ALLOW`. Returns ``"medium"``
        otherwise — the previous default for all callers.
        """
        lower = model_name.lower()
        if lower in _REASONING_EFFORT_OVERRIDE_ALLOW:
            return "medium"
        for pattern in _REASONING_EFFORT_UNSUPPORTED_PATTERNS:
            if pattern in lower:
                logger.info(
                    "reasoning_effort=None: model %r matches non-reasoning pattern %r",
                    model_name,
                    pattern,
                )
                return None
        return "medium"

    def __init__(
        self,
        *,
        model_name: str,
        provider_name: str,
        api_key: str,
        base_url: str | None = None,
        max_concurrency: int = 4,
        default_system: str = "You are a helpful assistant.",
        rate_limit_max_retries: int = 6,
        rate_limit_initial_backoff_seconds: float = 1.0,
        rate_limit_max_backoff_seconds: float = 60.0,
        reasoning_effort: str | None | Literal["auto"] = "auto",
    ) -> None:
        self.model_name = model_name
        self.provider_name = provider_name
        self.api_key = api_key
        self.base_url = base_url
        self._default_headers: dict[str, str] | None = None

        # `openai_codex` is clearwing's label for the OAuth-authenticated
        # Responses API (the ChatGPT "Codex CLI" flow). It's not a distinct
        # rust-genai adapter — it *is* the openai_resp adapter plus three
        # extra request headers (`chatgpt-account-id`, `OpenAI-Beta`,
        # `originator`) and a proxy base_url. Resolve the OAuth token and
        # account-id once here; from this point on the Client behaves
        # exactly like any other openai_resp Client.
        #
        # Token refresh happens once at construction. If the token expires
        # during a long-running AsyncLLMClient instance, subsequent calls
        # will fail until the instance is rebuilt — accepted tradeoff for
        # avoiding per-call refresh overhead.
        if provider_name == "openai_codex":
            from clearwing.providers.openai_oauth import (
                OPENAI_CODEX_DEFAULT_BASE_URL,
                ensure_fresh_openai_oauth_credentials,
                extract_account_id,
            )

            try:
                creds = ensure_fresh_openai_oauth_credentials()
                self.api_key = creds.access
            except Exception:
                if not self.api_key:
                    raise

            if not self.api_key:
                raise RuntimeError(
                    "Missing OpenAI OAuth access token. "
                    "Run: `clearwing setup --provider openai-oauth`"
                )

            account_id = extract_account_id(self.api_key)
            if not account_id:
                raise RuntimeError(
                    "OpenAI OAuth access token is missing the ChatGPT account id."
                )

            # Store the `.../codex/` base; `_build_client` derives the full
            # `.../codex/responses` URL and passes it (plus the OAuth headers)
            # to genai-pyo3 via `with_request_override`, so the native
            # transport talks to the ChatGPT backend directly.
            if not self.base_url:
                self.base_url = f"{OPENAI_CODEX_DEFAULT_BASE_URL}/codex/"
            elif not self.base_url.rstrip("/").endswith("/codex"):
                self.base_url = self.base_url.rstrip("/") + "/codex/"
            self._default_headers = {
                "ChatGPT-Account-ID": account_id,
                "originator": "codex_cli_rs",
                "User-Agent": "codex_cli_rs/0.0.0 (clearwing)",
            }

        if provider_name == "anthropic_oauth":
            from clearwing.providers.openai_oauth import (
                anthropic_oauth_headers,
                ensure_fresh_anthropic_oauth_credentials,
            )

            try:
                creds = ensure_fresh_anthropic_oauth_credentials()
                self.api_key = creds.token
            except Exception:
                if not self.api_key:
                    raise

            if not self.api_key:
                raise RuntimeError(
                    "Missing Anthropic OAuth token. "
                    "Run: `clearwing setup --provider anthropic-oauth`"
                )

            self._default_headers = anthropic_oauth_headers(self.api_key)
            self._anthropic_oauth_url = "https://api.anthropic.com/v1/messages"

        self.default_system = default_system
        # `reasoning_effort` controls how much reasoning the provider runs
        # (for models that support it). Accepted values: "none" | "minimal"
        # | "low" | "medium" | "high" | "xhigh" | "max" | "budget:<n>" | None.
        #
        # The sentinel "auto" (the default) lets the client pick based on the
        # model name — most non-OpenAI OpenAI-compat models reject this param
        # outright (see _REASONING_EFFORT_UNSUPPORTED_PATTERNS), so we omit it
        # for them while keeping "medium" everywhere else. Any explicit value
        # (including None) bypasses auto-resolution.
        if reasoning_effort == "auto":
            self.reasoning_effort = self._auto_resolve_reasoning_effort(model_name)
        else:
            self.reasoning_effort = reasoning_effort
        # Whether to request reasoning-content capture in ChatOptions. On for
        # every model except the blacklisted ones (see
        # _REASONING_CAPTURE_UNSUPPORTED_PATTERNS), which error if it's set.
        self.capture_reasoning_content = _model_supports_reasoning_capture(model_name)
        self.rate_limit_max_retries = max(0, rate_limit_max_retries)
        self.rate_limit_initial_backoff_seconds = max(0.1, rate_limit_initial_backoff_seconds)
        self.rate_limit_max_backoff_seconds = max(
            self.rate_limit_initial_backoff_seconds,
            rate_limit_max_backoff_seconds,
        )
        self._semaphore = asyncio.Semaphore(max(1, max_concurrency))
        self._spend_ledger: SpendLedger | None = None
        self._spend_stage = "llm"

    def with_spend_ledger(self, ledger: SpendLedger, *, stage: str) -> AsyncLLMClient:
        """Return a run-bound view that shares this client's transport limits.

        ProviderManager caches native clients process-wide.  A shallow view
        avoids mutating that shared client while retaining its semaphore and
        provider configuration for this Sourcehunt run.
        """

        ledger.validate_model(
            model=self.model_name,
            provider=self.provider_name,
            supports_output_limit=self.provider_name != "openai_codex",
        )
        bound = copy.copy(self)
        bound._spend_ledger = ledger
        bound._spend_stage = stage
        return bound

    @property
    def spend_ledger(self) -> SpendLedger | None:
        """The run-scoped ledger attached to this client view, if any."""

        return self._spend_ledger

    def _reserve_spend_call(
        self,
        *,
        messages: list[ChatMessage],
        system: str,
        tools: list[NativeToolSpec] | None,
        max_tokens: int | None,
    ) -> BudgetReservation | None:
        if self._spend_ledger is None:
            return None
        return self._spend_ledger.reserve_call(
            model=self.model_name,
            provider=self.provider_name,
            stage=self._spend_stage,
            input_token_upper_bound=self._request_input_token_upper_bound(
                messages=messages,
                system=system,
                tools=tools,
            ),
            requested_max_output_tokens=max_tokens,
            supports_output_limit=self.provider_name != "openai_codex",
            metadata=current_spend_metadata(),
        )

    @staticmethod
    def _request_input_token_upper_bound(
        *,
        messages: list[ChatMessage],
        system: str,
        tools: list[NativeToolSpec] | None,
    ) -> int:
        """Return a conservative provider-independent prompt token bound.

        Modern provider tokenizers encode text as one or more UTF-8 bytes per
        token.  Counting every serialized byte as a token, plus framing
        overhead, intentionally over-reserves without needing a model-specific
        tokenizer or a billable provider preflight request.
        """

        payload_messages: list[dict[str, Any]] = []
        for message in messages:
            item: dict[str, Any] = {
                "role": message.role,
                "content": message.content,
            }
            if message.tool_response_call_id:
                item["tool_call_id"] = message.tool_response_call_id
            if message.tool_calls:
                item["tool_calls"] = [
                    {
                        "id": call.call_id,
                        "name": call.fn_name,
                        "arguments": call.fn_arguments,
                    }
                    for call in message.tool_calls
                ]
            payload_messages.append(item)
        payload = {
            "system": system,
            "messages": payload_messages,
            "tools": [
                {
                    "name": tool.name,
                    "description": tool.description,
                    "schema": tool.schema,
                }
                for tool in tools or []
            ],
        }
        serialized_bytes = len(
            json.dumps(payload, ensure_ascii=False, default=str).encode("utf-8")
        )
        framing_overhead = 256 + 32 * len(messages) + 64 * len(tools or [])
        return serialized_bytes + framing_overhead

    def _settle_spend_call(
        self,
        reservation: BudgetReservation | None,
        response: ChatResponse,
    ) -> None:
        if reservation is None or self._spend_ledger is None:
            return
        usage = response.usage
        details = usage.prompt_tokens_details
        self._spend_ledger.settle_call(
            reservation,
            input_tokens=usage.prompt_tokens,
            output_tokens=usage.completion_tokens,
            cached_input_tokens=(
                details.cached_tokens if details is not None else None
            ),
        )

    def _fail_spend_call(
        self,
        reservation: BudgetReservation | None,
        exc: BaseException,
        *,
        dispatched: bool,
    ) -> None:
        if reservation is None or self._spend_ledger is None:
            return
        if not dispatched:
            self._spend_ledger.release_call(
                reservation,
                reason=type(exc).__name__,
            )
            return
        self._spend_ledger.fail_call(
            reservation,
            error=type(exc).__name__,
            definitely_unbilled=self._is_definitely_unbilled_error(exc),
        )

    def _is_definitely_unbilled_error(self, exc: BaseException) -> bool:
        """Return true only for provider rejections that precede generation."""

        if isinstance(exc, Exception) and self._is_rate_limit_error(exc):
            return True
        if self._is_unsupported_reasoning_effort_error(exc):
            return True
        text = str(exc).lower()
        return any(
            marker in text
            for marker in (
                "status code 400",
                "http 400",
                "status code 401",
                "http 401",
                "status code 403",
                "http 403",
                "status code 404",
                "http 404",
                "status code 422",
                "http 422",
            )
        )

    async def achat(
        self,
        *,
        messages: list[ChatMessage],
        system: str | None = None,
        tools: list[NativeToolSpec] | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        response_schema: type[BaseModel] | None = None,
        response_schema_name: str | None = None,
        response_schema_description: str | None = None,
    ) -> ChatResponse:
        request_tools = None
        if tools:
            request_tools = [
                Tool(
                    tool.name,
                    tool.description,
                    json.dumps(tool.schema),
                )
                for tool in tools
            ]

        system_prompt = system or self.default_system
        request = ChatRequest(
            messages=list(messages),
            system=system_prompt,
            tools=request_tools,
        )
        temperature, max_tokens = self._codex_safe_params(temperature, max_tokens)
        reservation = self._reserve_spend_call(
            messages=messages,
            system=system_prompt,
            tools=tools,
            max_tokens=max_tokens,
        )
        if reservation is not None and self._spend_ledger is not None:
            if self._spend_ledger.enforcing:
                max_tokens = reservation.max_output_tokens

        started = time.monotonic()
        dispatched = False
        try:
            options = ChatOptions(
                temperature=temperature,
                max_tokens=max_tokens,
                capture_content=True,
                capture_usage=True,
                capture_tool_calls=True,
                # Ask genai-pyo3 to surface the provider's reasoning output
                # (OpenAI Responses `reasoning.summary`, Anthropic thinking
                # blocks, etc.). `normalize_reasoning_content` unifies the
                # varied provider shapes into ChatResponse.reasoning_content,
                # so hunter transcripts see a single string regardless of
                # backend.
                capture_reasoning_content=self.capture_reasoning_content,
                normalize_reasoning_content=self.capture_reasoning_content,
                reasoning_effort=self.reasoning_effort,
                response_json_spec=(
                    _json_spec_from_model(
                        response_schema,
                        name=response_schema_name,
                        description=response_schema_description,
                    )
                    if response_schema is not None
                    else None
                ),
            )

            async with self._semaphore:
                client = self._build_client(Client)
                dispatched = True
                try:
                    response = await self._with_rate_limit_retries(
                        lambda: self._achat_with_provider_policy(client, request, options)
                    )
                except Exception as exc:
                    if not self._is_unsupported_reasoning_effort_error(exc):
                        raise
                    logger.warning(
                        "Provider rejected reasoning_effort for model %r; retrying "
                        "with reasoning_effort=None and disabling it for this session.",
                        self.model_name,
                    )
                    self.reasoning_effort = None
                    options = self._rebuild_options_without_reasoning(options)
                    response = await self._with_rate_limit_retries(
                        lambda: self._achat_with_provider_policy(client, request, options)
                    )
        except BaseException as exc:
            elapsed_ms = int((time.monotonic() - started) * 1000)
            self._fail_spend_call(reservation, exc, dispatched=dispatched)
            if _LOG_CALLS:
                logger.info(
                    "LLM %s failed in %dms: %s",
                    self.model_name,
                    elapsed_ms,
                    exc,
                )
            _record_call(self.model_name, elapsed_ms, None, None, 0, ok=False)
            raise

        self._settle_spend_call(reservation, response)
        usage = response.usage
        elapsed_ms = int((time.monotonic() - started) * 1000)
        prompt_tokens = usage.prompt_tokens
        completion_tokens = usage.completion_tokens
        details = usage.prompt_tokens_details
        cached_tokens = details.cached_tokens if details is not None else None
        n_tool_calls = len(response.tool_calls or [])
        if _LOG_CALLS:
            # The live LLM-activity panel already surfaces this per-call; keep
            # the line at DEBUG so it doesn't scroll over the pinned panel.
            logger.debug(
                "LLM %s %dms | msgs=%d tools=%d | in=%s out=%s | tool_calls=%d",
                self.model_name,
                elapsed_ms,
                len(messages),
                len(request_tools or []),
                prompt_tokens,
                completion_tokens,
                n_tool_calls,
            )
        _record_call(
            self.model_name,
            elapsed_ms,
            prompt_tokens,
            completion_tokens,
            n_tool_calls,
            ok=True,
            cached_tokens=cached_tokens,
        )
        return response

    async def achat_stream(
        self,
        *,
        messages: list[ChatMessage],
        system: str | None = None,
        tools: list[NativeToolSpec] | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        on_text_delta: Callable[[str], None] | None = None,
    ) -> ChatResponse:
        """Like ``achat`` but streams text deltas via *on_text_delta*.

        Uses genai-pyo3's native ``astream_chat``. Falls back to
        non-streaming ``achat`` when no callback is given.
        """
        if on_text_delta is None:
            return await self.achat(
                messages=messages,
                system=system,
                tools=tools,
                temperature=temperature,
                max_tokens=max_tokens,
            )

        request_tools = None
        if tools:
            request_tools = [
                Tool(tool.name, tool.description, json.dumps(tool.schema)) for tool in tools
            ]
        system_prompt = system or self.default_system
        request = ChatRequest(
            messages=list(messages),
            system=system_prompt,
            tools=request_tools,
        )
        temperature, max_tokens = self._codex_safe_params(temperature, max_tokens)
        reservation = self._reserve_spend_call(
            messages=messages,
            system=system_prompt,
            tools=tools,
            max_tokens=max_tokens,
        )
        if reservation is not None and self._spend_ledger is not None:
            if self._spend_ledger.enforcing:
                max_tokens = reservation.max_output_tokens

        started = time.monotonic()
        dispatched = False
        try:
            options = ChatOptions(
                temperature=temperature,
                max_tokens=max_tokens,
                capture_content=True,
                capture_usage=True,
                capture_tool_calls=True,
                capture_reasoning_content=self.capture_reasoning_content,
                normalize_reasoning_content=self.capture_reasoning_content,
                reasoning_effort=self.reasoning_effort,
            )
            async with self._semaphore:
                client = self._build_client(Client)

                async def _consume(opts: ChatOptions) -> ChatResponse | None:
                    nonlocal dispatched
                    dispatched = True
                    stream = await client.astream_chat(self.model_name, request, opts)
                    async for event in stream:
                        if event.content:
                            on_text_delta(event.content)
                        if event.end is not None:
                            return self._chat_response_from_stream_end(event.end)
                    return None

                try:
                    response = await _consume(options)
                except Exception as exc:
                    if self._is_unsupported_reasoning_effort_error(exc):
                        logger.warning(
                            "Provider rejected reasoning_effort (streaming) for model "
                            "%r; retrying with reasoning_effort=None and disabling it "
                            "for this session.",
                            self.model_name,
                        )
                        self.reasoning_effort = None
                        options = self._rebuild_options_without_reasoning(options)
                        response = await _consume(options)
                    elif self._should_try_openai_http_fallback(exc) and not (
                        self._spend_ledger is not None
                        and self._spend_ledger.enforcing
                    ):
                        logger.debug(
                            "Native OpenAI async stream failed for model=%s "
                            "base_url=%s; falling back to aiohttp "
                            "chat/completions: %s",
                            self.model_name,
                            self.base_url,
                            exc,
                        )
                        response = await self._openai_chat_http_fallback(
                            request,
                            options,
                            on_text_delta=on_text_delta,
                        )
                    else:
                        raise
                if response is None:
                    raise RuntimeError(
                        "LLM stream ended without a terminal usage event"
                    )
        except BaseException as exc:
            elapsed_ms = int((time.monotonic() - started) * 1000)
            self._fail_spend_call(reservation, exc, dispatched=dispatched)
            _record_call(self.model_name, elapsed_ms, None, None, 0, ok=False)
            if (
                "without a terminal usage event" in str(exc)
                and not (self._spend_ledger is not None and self._spend_ledger.enforcing)
            ):
                return await self.achat(
                    messages=messages,
                    system=system,
                    tools=tools,
                    temperature=temperature,
                    max_tokens=max_tokens,
                )
            raise

        self._settle_spend_call(reservation, response)
        usage = response.usage
        details = usage.prompt_tokens_details
        prompt_tokens = usage.prompt_tokens
        completion_tokens = usage.completion_tokens
        cached_tokens = details.cached_tokens if details is not None else None
        elapsed_ms = int((time.monotonic() - started) * 1000)
        _record_call(
            self.model_name,
            elapsed_ms,
            prompt_tokens,
            completion_tokens,
            len(response.tool_calls or []),
            ok=True,
            cached_tokens=cached_tokens,
        )
        return response

    def chat(self, **kwargs: Any) -> ChatResponse:
        return _run_coro_sync(self.achat(**kwargs))

    async def aask_text(
        self,
        *,
        system: str,
        user: str,
        temperature: float | None = None,
        max_tokens: int | None = None,
        response_schema: type[BaseModel] | None = None,
        response_schema_name: str | None = None,
        response_schema_description: str | None = None,
    ) -> ChatResponse:
        return await self.achat(
            messages=[ChatMessage("user", user)],
            system=system,
            temperature=temperature,
            max_tokens=max_tokens,
            response_schema=response_schema,
            response_schema_name=response_schema_name,
            response_schema_description=response_schema_description,
        )

    async def aask_json(
        self,
        *,
        system: str,
        user: str,
        expect: str = "object",
        temperature: float | None = None,
        max_tokens: int | None = None,
        schema_model: type[BaseModel] | None = None,
        schema_name: str | None = None,
        schema_description: str | None = None,
    ) -> tuple[Any, ChatResponse]:
        response = await self.aask_text(
            system=system,
            user=user,
            temperature=temperature,
            max_tokens=max_tokens,
            response_schema=schema_model,
            response_schema_name=schema_name,
            response_schema_description=schema_description,
        )
        text = response_text(response)
        if schema_model is not None:
            parsed_model = _validate_schema_response(schema_model, text)
            if _is_root_model_type(schema_model):
                return parsed_model.root, response
            return parsed_model.model_dump(), response
        if expect == "array":
            return extract_json_array(text), response
        return extract_json_object(text), response

    def _codex_safe_params(
        self, temperature: float | None, max_tokens: int | None
    ) -> tuple[float | None, int | None]:
        # The ChatGPT Codex (openai_codex) backend rejects `temperature` and
        # `max_output_tokens`, so omit both for that provider.
        if self.provider_name == "openai_codex":
            return None, None
        return temperature, max_tokens

    def _build_client(self, client_cls):
        # anthropic_oauth bypasses the normal auth resolver entirely —
        # with_request_override sends only our explicit headers (Bearer
        # token + beta flags), avoiding the ANTHROPIC_API_KEY env lookup.
        if self.provider_name == "anthropic_oauth":
            return client_cls.with_request_override(
                "anthropic",
                self._anthropic_oauth_url,
                self._default_headers or {},
            )

        # openai_codex (ChatGPT OAuth) is the openai_resp adapter pointed at
        # the ChatGPT backend's Responses endpoint. with_request_override sends
        # our exact URL + headers (Bearer token, ChatGPT-Account-ID, originator)
        # through genai-pyo3's native transport — verified to work end-to-end.
        # (The old aiohttp fallback blamed "Cloudflare 404s reqwest/HTTP2"; that
        # was a misdiagnosis — the real failures were missing headers and
        # unsupported body params, both handled here / in achat.)
        if self.provider_name == "openai_codex":
            base = (self.base_url or "https://chatgpt.com/backend-api/codex/").rstrip("/")
            if not base.endswith("/codex"):
                base = f"{base}/codex"
            responses_url = f"{base}/responses"
            headers = dict(self._default_headers or {})
            if self.api_key:
                headers["Authorization"] = f"Bearer {self.api_key}"
            return client_cls.with_request_override("openai_resp", responses_url, headers)

        rust_provider = self.provider_name
        default_headers = self._default_headers
        base_url = self.base_url
        if base_url:
            base_url = base_url if base_url.endswith("/") else f"{base_url}/"
            if self.api_key:
                return client_cls.with_api_key_and_base_url(
                    rust_provider,
                    self.api_key,
                    base_url,
                    default_headers=default_headers,
                    connect_timeout_seconds=_LLM_CONNECT_TIMEOUT_SECONDS,
                    read_timeout_seconds=_LLM_READ_TIMEOUT_SECONDS,
                    timeout_seconds=_LLM_TOTAL_TIMEOUT_SECONDS,
                )
            return client_cls.with_base_url(
                rust_provider,
                base_url,
                default_headers=default_headers,
                connect_timeout_seconds=_LLM_CONNECT_TIMEOUT_SECONDS,
                read_timeout_seconds=_LLM_READ_TIMEOUT_SECONDS,
                timeout_seconds=_LLM_TOTAL_TIMEOUT_SECONDS,
            )
        if self.api_key:
            return client_cls.with_api_key(
                rust_provider,
                self.api_key,
                default_headers=default_headers,
                connect_timeout_seconds=_LLM_CONNECT_TIMEOUT_SECONDS,
                read_timeout_seconds=_LLM_READ_TIMEOUT_SECONDS,
                timeout_seconds=_LLM_TOTAL_TIMEOUT_SECONDS,
            )
        raise RuntimeError(
            f"Cannot build LLM client for model={self.model_name} "
            f"provider={self.provider_name}: no API key or base URL configured. "
            f"Run `clearwing setup` or set ANTHROPIC_API_KEY / CLEARWING_BASE_URL."
        )

    async def _achat_with_provider_policy(
        self,
        client: Client,
        request: ChatRequest,
        options: ChatOptions,
    ) -> ChatResponse:
        # openai_resp / openai_codex (the Responses API + ChatGPT gateway)
        # require `stream=true` on the wire, so they go through
        # `achat_via_stream`: it streams internally and returns a fully
        # collected ChatResponse, so callers never see chunk events.
        #
        # Plain `openai` chat-completions is the exception. genai's streaming
        # path never sets stream_options.include_usage, so compatible gateways
        # drop the terminal usage chunk and ChatResponse.usage comes
        # back all-None (zeroing hunter totals, CostTracker, the activity
        # panel). A non-stream achat returns usage, so use it here. These
        # gateways can also be brittle on reqwest/HTTP2/SSE, so they keep the
        # aiohttp chat/completions fallback below.
        try:
            if self.provider_name == "openai":
                return await client.achat(self.model_name, request, options)
            return await client.achat_via_stream(self.model_name, request, options)
        except Exception as exc:
            if not self._should_try_openai_http_fallback(exc):
                raise
            if self._spend_ledger is not None and self._spend_ledger.enforcing:
                # The failed transport may already have reached the provider.
                # Retrying through another transport could incur a second bill;
                # let the ledger conservatively charge this reservation instead.
                raise
            logger.debug(
                "Native OpenAI streaming transport failed for model=%s base_url=%s; "
                "falling back to aiohttp chat/completions: %s",
                self.model_name,
                self.base_url,
                exc,
            )
            return await self._openai_chat_http_fallback(request, options)

    def _should_try_openai_http_fallback(self, exc: Exception) -> bool:
        if self.provider_name != "openai" or not self.base_url:
            return False

        text = str(exc).lower()
        return (
            "web stream error" in text
            or "web call failed" in text
            or "error sending request" in text
            or "http2" in text
            or "http/2" in text
            or "stream" in text
            or "reqwest error" in text
        )

    async def _openai_chat_http_fallback(
        self,
        request: ChatRequest,
        options: ChatOptions,
        *,
        on_text_delta: Callable[[str], None] | None = None,
    ) -> ChatResponse:
        """Fallback OpenAI chat-completions transport using aiohttp.

        This keeps Clearwing usable with OpenAI-compatible gateways that are
        correct enough for ordinary HTTP/1.1 clients but brittle with
        reqwest/HTTP2/SSE streaming. The fallback still returns genai-pyo3's
        ChatResponse so callers do not need provider-specific branches.
        """
        body = self._openai_chat_request_body(request, options, stream=on_text_delta is not None)
        headers = {
            "accept": "text/event-stream" if body.get("stream") else "application/json",
            "content-type": "application/json",
            "user-agent": "clearwing (aiohttp openai fallback)",
        }
        if self.api_key:
            headers["authorization"] = f"Bearer {self.api_key}"
        if self._default_headers:
            headers.update(self._default_headers)

        url = urljoin(
            self.base_url if self.base_url.endswith("/") else f"{self.base_url}/",
            "chat/completions",
        )
        timeout = aiohttp.ClientTimeout(total=600, sock_connect=30, sock_read=300)
        if body.get("stream"):
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(url, json=body, headers=headers) as resp:
                    if resp.status >= 400:
                        detail = (await resp.text())[:1000]
                        raise RuntimeError(
                            f"OpenAI-compatible fallback failed with HTTP {resp.status}: {detail}"
                        )
                    try:
                        return await self._collect_openai_sse_response(resp, on_text_delta)
                    except Exception:
                        logger.debug(
                            "OpenAI-compatible SSE fallback failed; retrying without streaming",
                            exc_info=True,
                        )

        body = self._openai_chat_request_body(request, options, stream=False)
        headers["accept"] = "application/json"
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(url, json=body, headers=headers) as resp:
                text = await resp.text()
                if resp.status >= 400:
                    raise RuntimeError(
                        f"OpenAI-compatible fallback failed with HTTP {resp.status}: {text[:1000]}"
                    )
                try:
                    payload = json.loads(text)
                except json.JSONDecodeError as exc:
                    raise RuntimeError(
                        f"OpenAI-compatible fallback returned non-JSON response: {text[:1000]}"
                    ) from exc
        response = self._chat_response_from_openai_payload(payload)
        if on_text_delta:
            visible = response.first_text or ""
            if visible:
                on_text_delta(visible)
        return response

    def _openai_chat_request_body(
        self,
        request: ChatRequest,
        options: ChatOptions,
        *,
        stream: bool,
    ) -> dict[str, Any]:
        messages: list[dict[str, Any]] = []
        if request.system:
            messages.append({"role": "system", "content": request.system})
        for message in request.messages():
            messages.append(self._openai_message_body(message))

        body: dict[str, Any] = {
            "model": self.model_name,
            "messages": messages,
            "stream": stream,
        }
        if stream and options.capture_usage:
            body["stream_options"] = {"include_usage": True}
        if options.temperature is not None:
            body["temperature"] = options.temperature
        if options.top_p is not None:
            body["top_p"] = options.top_p
        if options.max_tokens is not None:
            body["max_tokens"] = options.max_tokens
        if options.stop_sequences:
            body["stop"] = list(options.stop_sequences)
        if options.seed is not None:
            body["seed"] = options.seed
        if options.reasoning_effort:
            body["reasoning_effort"] = options.reasoning_effort
        if request.tools:
            body["tools"] = [self._openai_tool_body(tool) for tool in request.tools]
        if options.response_json_spec is not None:
            body["response_format"] = self._openai_response_format(options.response_json_spec)
        elif options.response_json_mode:
            body["response_format"] = {"type": options.response_json_mode}
        return body

    def _openai_message_body(self, message: ChatMessage) -> dict[str, Any]:
        body: dict[str, Any] = {"role": message.role, "content": message.content}
        if message.tool_response_call_id:
            body["tool_call_id"] = message.tool_response_call_id
        if message.tool_calls:
            body["tool_calls"] = [
                {
                    "id": call.call_id,
                    "type": "function",
                    "function": {
                        "name": call.fn_name,
                        "arguments": json.dumps(call.fn_arguments),
                    },
                }
                for call in message.tool_calls
            ]
        return body

    def _openai_tool_body(self, tool: Tool) -> dict[str, Any]:
        try:
            parameters = json.loads(tool.schema_json or "{}")
        except json.JSONDecodeError:
            parameters = {"type": "object", "properties": {}}
        return {
            "type": "function",
            "function": {
                "name": tool.name,
                "description": tool.description or "",
                "parameters": parameters,
            },
        }

    def _openai_response_format(self, spec: JsonSpec) -> dict[str, Any]:
        try:
            schema = json.loads(spec.schema_json)
        except json.JSONDecodeError:
            schema = {"type": "object"}
        json_schema: dict[str, Any] = {"name": spec.name, "schema": schema}
        if spec.description:
            json_schema["description"] = spec.description
        return {"type": "json_schema", "json_schema": json_schema}

    async def _collect_openai_sse_response(
        self,
        resp: aiohttp.ClientResponse,
        on_text_delta: Callable[[str], None] | None,
    ) -> ChatResponse:
        content_parts: list[str] = []
        reasoning_parts: list[str] = []
        tool_call_parts: dict[int, dict[str, Any]] = {}
        # Responses API SSE: keyed by output_index
        resp_tool_parts: dict[int, dict[str, Any]] = {}
        usage: dict[str, Any] | None = None
        provider_model = self.model_name
        is_responses_api = False
        final_response: dict[str, Any] | None = None

        async for raw_line in resp.content:
            line = raw_line.decode("utf-8", errors="replace").strip()
            if not line or not line.startswith("data:"):
                continue
            data = line[5:].strip()
            if data == "[DONE]":
                break
            try:
                chunk = json.loads(data)
            except json.JSONDecodeError:
                logger.debug("Skipping malformed OpenAI SSE chunk: %r", data)
                continue

            event_type = chunk.get("type") or ""
            if event_type.startswith("response."):
                is_responses_api = True
                if event_type == "response.done":
                    final_response = chunk.get("response") or chunk
                elif event_type == "response.output_text.delta":
                    text = chunk.get("delta") or ""
                    if text:
                        content_parts.append(text)
                        if on_text_delta:
                            on_text_delta(text)
                elif event_type == "response.output_item.added":
                    item = chunk.get("item") or {}
                    if item.get("type") == "function_call":
                        idx = int(chunk.get("output_index") or 0)
                        resp_tool_parts[idx] = {
                            "call_id": item.get("call_id") or item.get("id") or "",
                            "fn_name": item.get("name") or "",
                            "arguments": item.get("arguments") or "",
                        }
                elif event_type == "response.function_call_arguments.delta":
                    idx = int(chunk.get("output_index") or 0)
                    acc = resp_tool_parts.setdefault(idx, {"call_id": chunk.get("call_id") or "", "fn_name": "", "arguments": ""})
                    acc["arguments"] += chunk.get("delta") or ""
                elif event_type == "response.function_call_arguments.done":
                    idx = int(chunk.get("output_index") or 0)
                    acc = resp_tool_parts.setdefault(idx, {"call_id": chunk.get("call_id") or "", "fn_name": "", "arguments": ""})
                    acc["arguments"] = chunk.get("arguments") or acc["arguments"]
                continue

            provider_model = chunk.get("model") or provider_model
            if chunk.get("usage"):
                usage = chunk["usage"]
            for choice in chunk.get("choices") or []:
                delta = choice.get("delta") or {}
                text = delta.get("content")
                if text:
                    content_parts.append(text)
                    if on_text_delta:
                        on_text_delta(text)
                reasoning = delta.get("reasoning_content") or delta.get("reasoning")
                if reasoning:
                    reasoning_parts.append(reasoning)
                self._merge_openai_tool_call_deltas(tool_call_parts, delta.get("tool_calls"))

        if is_responses_api:
            if final_response:
                return self._chat_response_from_responses_payload(final_response)
            tool_calls = [
                {
                    "call_id": part["call_id"],
                    "fn_name": part["fn_name"],
                    "fn_arguments": self._parse_openai_tool_arguments(part["arguments"]),
                }
                for part in (v for _, v in sorted(resp_tool_parts.items()))
            ]
            return self._chat_response_from_parts(
                text="".join(content_parts),
                reasoning_content=None,
                tool_calls=tool_calls,
                usage=usage,
                provider_model=provider_model,
            )

        return self._chat_response_from_parts(
            text="".join(content_parts),
            reasoning_content="".join(reasoning_parts) or None,
            tool_calls=self._finalize_openai_tool_calls(tool_call_parts),
            usage=usage,
            provider_model=provider_model,
        )

    def _chat_response_from_openai_payload(self, payload: dict[str, Any]) -> ChatResponse:
        if "output" in payload or payload.get("object") == "response":
            return self._chat_response_from_responses_payload(payload)
        choice = (payload.get("choices") or [{}])[0]
        message = choice.get("message") or {}
        text = self._extract_openai_message_text(message.get("content"))
        reasoning_content = message.get("reasoning_content") or message.get("reasoning")
        tool_calls = self._openai_tool_calls_from_message(message.get("tool_calls") or [])
        return self._chat_response_from_parts(
            text=text,
            reasoning_content=reasoning_content,
            tool_calls=tool_calls,
            usage=payload.get("usage"),
            provider_model=payload.get("model") or self.model_name,
        )

    def _chat_response_from_responses_payload(self, payload: dict[str, Any]) -> ChatResponse:
        """Parse an OpenAI Responses API (non-streaming) payload into ChatResponse."""
        text_parts: list[str] = []
        reasoning_parts: list[str] = []
        tool_calls: list[dict[str, Any]] = []
        for item in payload.get("output") or []:
            item_type = item.get("type")
            if item_type == "message":
                for part in item.get("content") or []:
                    part_type = part.get("type")
                    if part_type in ("output_text", "text"):
                        text_parts.append(part.get("text") or "")
                    elif part_type in ("reasoning", "thinking"):
                        reasoning_parts.append(part.get("text") or part.get("thinking") or "")
            elif item_type == "function_call":
                tool_calls.append({
                    "call_id": item.get("call_id") or item.get("id") or "",
                    "fn_name": item.get("name") or "",
                    "fn_arguments": self._parse_openai_tool_arguments(item.get("arguments")),
                })
            elif item_type == "reasoning":
                for summary in item.get("summary") or []:
                    reasoning_parts.append(summary.get("text") or "")
        return self._chat_response_from_parts(
            text="".join(text_parts),
            reasoning_content="".join(reasoning_parts) or None,
            tool_calls=tool_calls,
            usage=payload.get("usage"),
            provider_model=payload.get("model") or self.model_name,
        )

    def _extract_openai_message_text(self, content: Any) -> str:
        if content is None:
            return ""
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            parts: list[str] = []
            for item in content:
                if isinstance(item, str):
                    parts.append(item)
                elif isinstance(item, dict):
                    text = item.get("text") or item.get("content")
                    if isinstance(text, str):
                        parts.append(text)
            return "".join(parts)
        return str(content)

    def _openai_tool_calls_from_message(self, tool_calls: list[dict[str, Any]]) -> list[dict[str, Any]]:
        parsed: list[dict[str, Any]] = []
        for call in tool_calls:
            fn = call.get("function") or {}
            parsed.append(
                {
                    "call_id": call.get("id") or "",
                    "fn_name": fn.get("name") or call.get("name") or "",
                    "fn_arguments": self._parse_openai_tool_arguments(
                        fn.get("arguments") if "arguments" in fn else call.get("arguments")
                    ),
                }
            )
        return parsed

    def _merge_openai_tool_call_deltas(
        self,
        tool_call_parts: dict[int, dict[str, Any]],
        deltas: list[dict[str, Any]] | None,
    ) -> None:
        for delta in deltas or []:
            index = int(delta.get("index") or 0)
            acc = tool_call_parts.setdefault(index, {"arguments": ""})
            if delta.get("id"):
                acc["id"] = delta["id"]
            fn = delta.get("function") or {}
            if fn.get("name"):
                acc["name"] = fn["name"]
            if fn.get("arguments"):
                acc["arguments"] += fn["arguments"]

    def _finalize_openai_tool_calls(
        self,
        tool_call_parts: dict[int, dict[str, Any]],
    ) -> list[dict[str, Any]]:
        return [
            {
                "call_id": part.get("id") or "",
                "fn_name": part.get("name") or "",
                "fn_arguments": self._parse_openai_tool_arguments(part.get("arguments")),
            }
            for _, part in sorted(tool_call_parts.items())
        ]

    def _parse_openai_tool_arguments(self, value: Any) -> Any:
        if value is None:
            return {}
        if isinstance(value, str):
            if not value:
                return {}
            try:
                return json.loads(value)
            except json.JSONDecodeError:
                return value
        return value

    def _chat_response_from_stream_end(self, end: StreamEnd) -> ChatResponse:
        """Adapt a genai-pyo3 ``StreamEnd`` into a ``ChatResponse``.

        ``astream_chat`` yields a ``StreamEnd`` (whose fields are named
        ``captured_*``) at the end of the stream — not a ``ChatResponse``.
        Callers expect the same interface ``achat`` returns (``first_text``,
        ``tool_calls``, ``usage`` …), so rebuild a ``ChatResponse`` from the
        captured content rather than leaking the ``StreamEnd`` shape.
        """
        return ChatResponse(
            content=end.captured_content,
            reasoning_content=end.captured_reasoning_content,
            response_id=end.captured_response_id,
            model_name=self.model_name,
            provider_model_name=self.model_name,
            usage=end.captured_usage,
        )

    def _chat_response_from_parts(
        self,
        *,
        text: str,
        reasoning_content: str | None,
        tool_calls: list[dict[str, Any]],
        usage: dict[str, Any] | None,
        provider_model: str,
    ) -> ChatResponse:
        content: list[dict[str, Any]] = []
        if text:
            content.append({"text": text})
        for call in tool_calls:
            if call["call_id"] and call["fn_name"]:
                content.append({"tool_call": call})
        return ChatResponse(
            content=content or None,
            reasoning_content=reasoning_content,
            model_adapter_kind="openai",
            model_name=self.model_name,
            provider_model_adapter_kind="openai",
            provider_model_name=provider_model,
            usage=self._usage_from_openai_payload(usage),
        )

    def _usage_from_openai_payload(self, usage: dict[str, Any] | None) -> Usage:
        usage = usage or {}
        return Usage(
            prompt_tokens=usage.get("prompt_tokens"),
            completion_tokens=usage.get("completion_tokens"),
            total_tokens=usage.get("total_tokens"),
        )

    async def _with_rate_limit_retries(self, op) -> ChatResponse:
        attempt = 0
        while True:
            try:
                return await op()
            except Exception as exc:
                if not self._is_rate_limit_error(exc) or attempt >= self.rate_limit_max_retries:
                    raise

                delay = self._retry_delay_seconds(exc, attempt)
                attempt += 1
                logger.warning(
                    "LLM call rate-limited for model=%s provider=%s; retrying in %.2fs (attempt %d/%d): %s",
                    self.model_name,
                    self.provider_name,
                    delay,
                    attempt,
                    self.rate_limit_max_retries,
                    exc,
                )
                await asyncio.sleep(delay)

    @staticmethod
    def _rebuild_options_without_reasoning(options: ChatOptions) -> ChatOptions:
        """Return a copy of *options* with ``reasoning_effort=None``.

        ``ChatOptions`` is a frozen Rust struct from genai-pyo3, so we
        reconstruct it from scratch. ``response_json_spec`` is preserved.
        """
        return ChatOptions(
            temperature=options.temperature,
            max_tokens=options.max_tokens,
            capture_content=options.capture_content,
            capture_usage=options.capture_usage,
            capture_tool_calls=options.capture_tool_calls,
            capture_reasoning_content=options.capture_reasoning_content,
            normalize_reasoning_content=options.normalize_reasoning_content,
            reasoning_effort=None,
            response_json_spec=options.response_json_spec,
        )

    @staticmethod
    def _is_unsupported_reasoning_effort_error(exc: BaseException) -> bool:
        """True when *exc* indicates the provider rejected ``reasoning_effort``.

        Both conditions required: ``"reasoning_effort"`` must appear in the
        message AND either ``"400"`` (the HTTP status) or ``"unsupported"``.
        This avoids false positives on log lines or unrelated errors that
        merely mention the parameter name.
        """
        text = str(exc).lower()
        if "reasoning_effort" not in text:
            return False
        return "400" in text or "unsupported" in text

    def _is_rate_limit_error(self, exc: Exception) -> bool:
        text = str(exc).lower()
        return (
            " 429" in text
            or text.startswith("429")
            or "status code 429" in text
            or "too many requests" in text
            or "rate limit" in text
            or "ratelimit" in text
        )

    def _retry_delay_seconds(self, exc: Exception, attempt: int) -> float:
        retry_after = self._parse_retry_after_seconds(str(exc))
        if retry_after is not None:
            base_delay = retry_after
        else:
            base_delay = min(
                self.rate_limit_initial_backoff_seconds * (2**attempt),
                self.rate_limit_max_backoff_seconds,
            )

        jitter = min(1.0, base_delay * 0.2) * random.random()
        return min(base_delay + jitter, self.rate_limit_max_backoff_seconds)

    def _parse_retry_after_seconds(self, text: str) -> float | None:
        patterns = [
            r"retry[- ]after[:=]?\s*([0-9]+(?:\.[0-9]+)?)",
            r"try again in\s*([0-9]+(?:\.[0-9]+)?)s",
            r"wait\s*([0-9]+(?:\.[0-9]+)?)s",
        ]
        lowered = text.lower()
        for pattern in patterns:
            match = re.search(pattern, lowered)
            if match:
                try:
                    return float(match.group(1))
                except ValueError:
                    return None
        return None


def extract_json_object(text: str) -> dict[str, Any]:
    match = re.search(r"\{[\s\S]*\}", text)
    if not match:
        raise ValueError("response did not contain a JSON object")
    parsed = json.loads(match.group(0))
    if not isinstance(parsed, dict):
        raise ValueError("response JSON was not an object")
    return parsed


def extract_json_array(text: str) -> list[Any]:
    match = re.search(r"\[[\s\S]*\]", text)
    if not match:
        raise ValueError("response did not contain a JSON array")
    parsed = json.loads(match.group(0))
    if not isinstance(parsed, list):
        raise ValueError("response JSON was not an array")
    return parsed


def _json_spec_from_model(
    schema_model: type[BaseModel],
    *,
    name: str | None = None,
    description: str | None = None,
) -> JsonSpec:
    schema = schema_model.model_json_schema()
    return JsonSpec(
        name=name or _schema_name_for_model(schema_model),
        schema_json=json.dumps(schema),
        description=description,
    )


def _schema_name_for_model(schema_model: type[BaseModel]) -> str:
    raw_name = getattr(schema_model, "__name__", "response_schema")
    normalized = re.sub(r"[^A-Za-z0-9_-]+", "_", raw_name).strip("_")
    return normalized or "response_schema"
